<QR_code_Grid>:
    id:qr_widget
    background_color: (1,0,0,1)
    name:name
    url:url
    Label:
        text: "Name of qr_code:"
        font_size: 16
        pos: "65dp", "400dp"

    TextInput:
        id:name
        multiline:False
        pos: "50dp", "395dp"
        size: "200dp","35dp"
        font_size: 16

    Label:
        text: "URL/link:"
        font_size: 16
        pos: "35dp", "320dp"
        size_hint: .8, .5

    TextInput:
        id:url
        multiline:False
        pos: "50dp", "320dp"
        size: "350dp","35dp"
        font_size: 16


    Button:
        text:"Get your qr code"
        size: "200dp","35dp"
        pos: "50dp", "280dp"
        on_press: root.press()


